In [2]:
# Check Pytorch installation
import torch, torchvision
print(torch.__version__, torch.cuda.is_available())

# Check MMDetection installation
import mmdet
print(mmdet.__version__)

# Check mmcv installation
from mmcv.ops import get_compiling_cuda_version, get_compiler_version
print(get_compiling_cuda_version())
print(get_compiler_version())

1.11.0+cu115 True
2.23.0
11.6
GCC 9.4


In [3]:
from mmcv import collect_env
collect_env()

{'sys.platform': 'linux',
 'Python': '3.7.13 (default, Mar 29 2022, 02:18:16) [GCC 7.5.0]',
 'CUDA available': True,
 'GPU 0,1,2,3': 'NVIDIA TITAN Xp',
 'CUDA_HOME': '/usr/local/cuda',
 'NVCC': 'Build cuda_11.6.r11.6/compiler.30978841_0',
 'GCC': 'gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0',
 'PyTorch': '1.11.0+cu115',
 'PyTorch compiling details': 'PyTorch built with:\n  - GCC 7.3\n  - C++ Version: 201402\n  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications\n  - Intel(R) MKL-DNN v2.5.2 (Git Hash a9302535553c73243c632ad3c4c80beec3d19a1e)\n  - OpenMP 201511 (a.k.a. OpenMP 4.5)\n  - LAPACK is enabled (usually provided by MKL)\n  - NNPACK is enabled\n  - CPU capability usage: AVX2\n  - CUDA Runtime 11.5\n  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=comp

In [3]:
heads = {'ct_hm': 80, 'bus': 10}
for head in heads:
    print(heads[head])
    print('ct' in head)

80
True
10
False


In [8]:
import torch
a = torch.tensor([[2,1],[5,4]])
b = torch.tensor([[1],[2]])
a + b

In [9]:
c = a
c[0][0] = 1
c

tensor([[3, 2],
        [7, 6]])

In [13]:
print('a size:',a.shape,a)

a size: torch.Size([2, 2]) tensor([[2, 1],
        [5, 4]])


In [10]:
class Dog():
    def __init__(self, name):
        self.name = name
    def introduce(self):
        print(f"The dog's name is {self.name}")

In [11]:
dog = Dog('Tom')

In [20]:
class RedDog(Dog):
    def __init__(self, name):
        super().__init__(name)
    def introduce(self):
        print(f"The RedDog's name is {self.name}")

In [21]:
newdog=RedDog('Sam')

In [22]:
newdog.introduce()

The RedDog's name is Sam


In [1]:
import pickle

In [5]:
with open("/home/sjtu/scratch/tongzhao/e2ec/network/batch.pkl", "rb") as tf:
    new_dict = pickle.load(tf)

EOFError: Ran out of input

In [ ]:
print(new_dict.item())

In [6]:
import numpy as np

new_dict = np.load('/home/sjtu/scratch/tongzhao/e2ec/network/batch.npy', allow_pickle='TRUE')
print(new_dict)

{'inp': tensor([[[[-1.9693, -1.9693, -1.9693,  ..., -1.9693, -1.9693, -1.9693],
          [-1.9693, -1.9693, -1.9693,  ..., -1.9693, -1.9693, -1.9693],
          [-1.9693, -1.9693, -1.9693,  ..., -1.9693, -1.9693, -1.9693],
          ...,
          [-1.9693, -1.9693, -1.9693,  ..., -1.9693, -1.9693, -1.9693],
          [-1.9693, -1.9693, -1.9693,  ..., -1.9693, -1.9693, -1.9693],
          [-1.9693, -1.9693, -1.9693,  ..., -1.9693, -1.9693, -1.9693]],

         [[-2.2217, -2.2217, -2.2217,  ..., -2.2217, -2.2217, -2.2217],
          [-2.2217, -2.2217, -2.2217,  ..., -2.2217, -2.2217, -2.2217],
          [-2.2217, -2.2217, -2.2217,  ..., -2.2217, -2.2217, -2.2217],
          ...,
          [-2.2217, -2.2217, -2.2217,  ..., -2.2217, -2.2217, -2.2217],
          [-2.2217, -2.2217, -2.2217,  ..., -2.2217, -2.2217, -2.2217],
          [-2.2217, -2.2217, -2.2217,  ..., -2.2217, -2.2217, -2.2217]],

         [[-2.2739, -2.2739, -2.2739,  ..., -2.2739, -2.2739, -2.2739],
          [-2.2739, -2

In [1]:
import torch

In [14]:
kity = torch.tensor([[3,3,3],[1,2,3]])
ad = torch.ones_like(kity)
ad % 10

tensor([[1, 1, 1],
        [1, 1, 1]])

In [2]:
import torch
a = torch.tensor([[1,1],[1,0.9]])
b = torch.tensor([[1,0.4],[0.4,1]])
a

tensor([[1.0000, 1.0000],
        [1.0000, 0.9000]])

In [14]:
b

tensor([[1.0000, 0.4000],
        [0.4000, 1.0000]])

In [15]:
b.shape

torch.Size([2, 2])

In [17]:
b.view([1,4])

tensor([[1.0000, 0.4000, 0.4000, 1.0000]])

In [5]:
y = (a == b).float()
y

tensor([[1., 0.],
        [0., 0.]])

In [3]:
heat_map = torch.rand([128,128,80])
pred_wh = torch.rand([128,128,2])
pred_offset = torch.rand([128,128,2])

In [4]:
heat_map

tensor([[[1.1532e-01, 8.0931e-01, 4.5834e-02,  ..., 4.6827e-01,
          1.0170e-01, 9.5791e-01],
         [7.1485e-01, 4.2354e-01, 1.9640e-02,  ..., 1.6906e-01,
          4.3480e-01, 1.9607e-01],
         [7.0478e-01, 1.4229e-01, 2.8003e-01,  ..., 7.1566e-01,
          2.3429e-01, 9.6041e-01],
         ...,
         [4.7963e-01, 1.6700e-01, 7.0979e-01,  ..., 6.9375e-01,
          7.2404e-01, 1.2274e-01],
         [5.3529e-01, 1.1812e-01, 9.1527e-01,  ..., 8.2017e-01,
          2.8131e-01, 6.8607e-01],
         [6.3598e-01, 9.9885e-01, 5.6937e-01,  ..., 5.9347e-01,
          4.0778e-01, 1.8332e-01]],

        [[8.7984e-02, 4.0379e-01, 1.1346e-01,  ..., 5.7943e-01,
          5.5448e-01, 3.1119e-01],
         [9.7374e-01, 3.4503e-01, 7.3437e-01,  ..., 4.9221e-01,
          8.0825e-01, 2.1281e-01],
         [7.9451e-01, 3.9300e-01, 6.6823e-02,  ..., 8.7284e-01,
          5.6433e-02, 3.5212e-02],
         ...,
         [8.9293e-01, 9.4361e-01, 1.7698e-01,  ..., 2.4701e-01,
          8.935

In [16]:
yv, xv = torch.meshgrid(torch.arange(0, 128), torch.arange(0,128))

In [6]:
# xv = xv.flatten().float()
# yv = yv.flatten().float()

In [7]:
yv.shape

torch.Size([16384])

In [97]:
torch.max(heat_map,dim=-1)

torch.return_types.max(
values=tensor([[0.9972, 0.9864, 0.9823,  ..., 0.9826, 0.9907, 0.9879],
        [0.9937, 0.9989, 0.9947,  ..., 0.9848, 0.9994, 0.9669],
        [0.9940, 0.9950, 0.9993,  ..., 0.9941, 0.9820, 0.9995],
        ...,
        [0.9882, 0.9942, 0.9952,  ..., 0.9972, 0.9847, 0.9925],
        [0.9902, 0.9960, 0.9994,  ..., 0.9795, 0.9920, 0.9743],
        [0.9874, 0.9951, 0.9811,  ..., 0.9846, 0.9988, 0.9825]]),
indices=tensor([[34, 45, 67,  ..., 75, 26, 29],
        [68, 19, 75,  ..., 39, 71, 48],
        [58, 47, 14,  ...,  3, 12, 62],
        ...,
        [76, 70, 67,  ..., 53, 60, 53],
        [21, 60, 37,  ..., 40, 59,  1],
        [11, 28, 72,  ..., 79,  1, 70]]))

In [8]:
class_conf, class_pred = torch.max(heat_map,dim=-1)

In [9]:
mask = class_conf > 0.995

In [10]:
mask.shape

torch.Size([128, 128])

In [11]:
pred_wh_mask = pred_wh[mask]
pred_offset_mask = pred_offset[mask]

In [12]:
pred_offset_mask.shape

torch.Size([5482, 2])

In [17]:
xv[mask]

tensor([  2,   5,   8,  ..., 123, 126, 127])

In [32]:
xv_mask = torch.unsqueeze(xv[mask] + pred_offset_mask[..., 0],-1)

In [33]:
yv_mask = torch.unsqueeze(yv[mask] + pred_offset_mask[..., 1],-1)

In [34]:
half_w, half_h = pred_wh_mask[...,0] / 2, pred_wh_mask[...,1] / 2

In [38]:
xv_mask.shape


torch.Size([5482])

In [ ]:
half_w.shape

In [35]:
bboxes = torch.cat([xv_mask - half_w, yv_mask - half_h, xv_mask + half_w, yv_mask + half_h], dim=1)

In [42]:
bboxes.shape

torch.Size([5482, 21928])

In [41]:
(xv_mask - half_w).shape

torch.Size([5482, 5482])